#=============================================
# Define Crystal Parameters
#=============================================

omega0:   6952.1444886372155   #central photon energy

a0: 3.5668194616854 #Diamond lattice constant in A

#  Refraction index n = 1 - delta - i*beta :
#  from XOP toolkit-> Optics -> Crystals -> XINPRO
delta: 1.5151703820770685E-005
beta:  3.3935688676952351E-008


# susceptibilties from XOP toolkit-> Optics -> Crystals -> XINPRO
xrh: 1.0332514501357626E-005
xih: 6.6646704491991106E-008

#xrh: 2.978624e-06
#xih: 1.1292e-08
#reflection type
Miller_h: 2
Miller_k: 2
Miller_l: 0

# crystal thickness in microns and
thickness: 400
asymm_angle: 88.0 #deg

#Grid parameters, number of grid points
xgrid: 1000
ygrid: 3

# simulation  window size in micron
xxmax: 2200 
yymax: 1000

#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.125 #  defined as:
 #Z = np.abs(Zstep_factor * np.pi/np.real((delta - 1i*beta)**2))/k  #  Z - step in z
method: 'Verlet'
#Mode: TIDP, TDP
mode: 'TIDP'
# number of propagation steps
M: 1600
#M: 'auto'
tpad: 4096
# type of x-ray beam
beam: 'Gaussian'

slit_x: 10000 # microns slit width
slit_y: 10000 # microns slit widt
# x00: 'auto'
x00: -100  # initial beam position in microns
waist: 4000 #microns
#pump from file GenesisV2
# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0
#Deformation of lattice: None, Sinusoidal, 
#deformation: 'None'
deformation: 'B dopped Diamond Laue'
# sinusoidal deformation paramters
def_amplitude: 0.5e-10
def_period: 4.0
#constant stress gradient parameter
def_B: 0.25
dudz: 0.00
depth: -40
B_size: 100
CrSize: 800
#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 1 # separation between number of steps in z for which the field distribution is saved