#=============================================
# Define Crystal Parameters
#=============================================

omega0: 12800.0  #central photon energy

a0: 3.56679 #Diamond lattice constant in A
 

#  Refraction index = 1 - delta - i*beta :

delta: 4.45674658655637046E-006
beta:  2.85960537412047332E-009


xrh: 0.145194E-05
xih: 0.318424E-08  

Miller_h: 3
Miller_k: 3
Miller_l: 3

# crystal thickness in microns
thickness: 100 

#Grid parameters
xgrid: 4000
ygrid: 1

#size in micron
xxmax: 2000
yymax: 10
#yymax: 10 

x00: -1000

#Grid resolution
res_x: 33333
res_y: 1
#res_y: 10

tpad: 4096

#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.1
method: 'Forest-Ruth'
#Mode: TIDP, TDP
mode: 'TIDP'

beam: 'Gaussian'
waist: 500.0

#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0


#Deformation of lattice: None, Sinusoidal, 
deformation: 'None'
def_amplitude: 0.0
def_period: 4.0

#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 100
