#=============================================
# Define Crystal Parameters
#=============================================

omega0: 9831.0  #central photon energy

a0: 3.5668194616854 #Diamond lattice constant in A

#  Refraction index n = 1 - delta - i*beta :
delta1: 7.5628e-06
beta1:  7.32545e-09
xrh1: 0.372328E-05
xih1: 0.141150E-07

delta2: 7.5628e-06
beta2:  7.32545e-09
xrh2: 0.372328E-05
xih2: 0.141150E-07

Miller_h: 4
Miller_k: 0
Miller_l: 0

# crystal thickness in microns
thickness: 82
d_film: 0
xs: 0   # moving crystal 0 um with respect to origin in x-coordinate
separation1: 0
separation2: 0
asymm_angle: 90.0
#Grid parameters
xgrid: 4000
ygrid: 1

#size in micron
xxmax: 4000 
yymax: 10
#yymax: 10 

#x00: 'auto'
x00: -500

#Grid resolution
res_x: 33333
res_y: 10
#res_y: 10
M: 4000
#M: 'auto'
tpad: 4096

#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.05
method: 'Verlet'
#Mode: TIDP, TDP
mode: 'TIDP'

beam: 'Gaussian'
waist: 3000 #microns
slit_x: 100000 # microns slit width
slit_y: 100000 # microns slit width
#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0


#Deformation of lattice: None, Sinusoidal, 
deformation: 'None'
strain: 0
x0d: 0
y0d: -0 #y coordinate of dislocatio in um
z0d: -0 #z coordinate of dislocatio in um
slope: 0.0
phid: 1.5707963267948966 #orientation of dislocation
#phid: 0 #orientation of dislocation
burgers_vector_x: 1.9200423982948915 # a0/2/sqrt(2) in A, x-component mixed 60 deg dislocation 
burgers_vector_screw: 3.840084796589783 # a0/sqrt(2) in A           
v: 0.22 # Poisson ratio
dudz: 0.00
depth: 0
B_size: 100
CrSize: 800000
def_amplitude: 0.5e-10
def_period: 4.0
def_B: 0.25
#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 1