#=============================================
# Define Crystal Parameters
#=============================================

omega0: 9831.0  #central photon energy

a0: 3.5668 #Diamond lattice constant in A

#  Refraction index = 1 - delta - i*beta :
delta: 7.56212152208668442E-006
beta:  8.17643864117176264E-009

xrh: 0.372328E-05
xih: 0.141150E-07

Miller_h: 4
Miller_k: 0
Miller_l: 0

# crystal thickness in microns
thickness: 100 

#Grid parameters
xgrid: 3200
ygrid: 10

#size in micron
xxmax: 1200 
yymax: 10
#yymax: 10 

x00: -600

#Grid resolution
res_x: 33333
res_y: 10
#res_y: 10

tpad: 4096

#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.125
method: 'Forest-Ruth'
#Mode: TIDP, TDP
mode: 'TIDP'

beam: 'Gaussian'
waist: 250.0

#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0


#Deformation of lattice: None, Sinusoidal, 
deformation: 'None'
def_amplitude: 0.5e-10
def_period: 4.0
def_B: 0.25
#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 30
