#=============================================
# Define Crystal Parameters
#=============================================

omega0: 14000  #central photon energy

a0:   4.4582987999999997 #LiNbOin A

#  Refraction index = 1 - delta - i*beta :

#for LiNbO
delta1: 4.4425428181746958E-006 
beta1:  6.4930780402048248E-008
xrh1:   2.8722226912914497E-006
xih1:   1.2392944605404412E-007

#for STO
delta2: 0.96661E-05 
beta2: 0.29554E-06
xrh2:  0.12591E-04
xih2:  0.57649E-06



Miller_h: 2
Miller_k: 2
Miller_l: 0

# crystal thickness in microns
thickness: 4.0e-4
d_film: 0.04
xs: 2.0e-4   # moving crystal 2 um with respect to origin in x-coordinate
asymm_angle: 0
#Grid prameters
xgrid: 6000
ygrid: 1

#size in micron
xxmax: 3 
yymax: 0.0001
#yymax: 10 



tpad: 512


#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.002
method: 'Euler'

#Mode: TIDP, TDP
mode: 'TIDP'
M: 600
#M: 'auto'
beam: 'Gaussian'
slit_x: 5 # microns slit width
slit_y: 100000 # microns slit width
waist: 0.5
# x00: 'auto'
x00: -1.3
#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0


#Deformation of lattice: None, Sinusoidal, 
#deformation: 'None'
deformation: 'Strained film'
#strain: 0.0091
strain: 0.00
def_B: 0.25  # strain gradient parameter
R: 100000000000000000000000000000 # crystal bend redius in m
vC100: 0.008 #the Poisson ratio
def_amplitude: 0.0
def_period: 4.0

x0d: 0
y0d: -0 #y coordinate of dislocatio in um
z0d: -0 #z coordinate of dislocatio in um
slope: 0.0
phid: 1.5707963267948966 #orientation of dislocation
#phid: 0 #orientation of dislocation
burgers_vector_x: 1.9200423982948915 # a0/2/sqrt(2) in A, x-component mixed 60 deg dislocation 
burgers_vector_screw: 3.840084796589783 # a0/sqrt(2) in A           
vC: 0.22 # Poisson ratio
dudz: 0.00
depth: 0
B_size: 100
CrSize: 800000
def_amplitude: 0.5e-10
def_period: 4.0
def_B: 0.25
#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 1
