#=============================================
# Define Crystal Parameters
#=============================================

omega0: 9000.0  #central photon energy

a0: 5.4307 #Silicon lattice constant in A

#  Refraction index = 1 - delta - i*beta :
delta: 6.07112469641624131E-006
beta: 1.11623508050849052E-007

xrh: 0.605243E-05
xih: 0.212281E-06

Miller_h: 4
Miller_k: 0
Miller_l: 0

# crystal thickness in microns
thickness: 50 
separation1: 0
separation2: 0
#Grid parameters
xgrid: 5200
ygrid: 1

#size in micron
xxmax: 1200 
yymax: 150
#yymax: 10 
x00: -300

#Grid resolution
res_x: 555555
res_y: 1234567
#res_y: 10

tpad: 512


#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.1
method: 'Euler'
#Mode: TIDP, TDP
mode: 'TIDP'

beam: 'Gaussian'
waist: 150.0

#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0
M: 'auto'

#Deformation of lattice: None, Sinusoidal, ConstStrainGrad
deformation: 'None'
def_amplitude: 1e-10
def_period: 4.0
def_B: 0.05
#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 100
