#=============================================
# Define Crystal Parameters
#=============================================

omega0: 8048.0  #central photon energy

a0: 5.4307 #Silicon lattice constant in A

#  Refraction index = 1 - delta - i*beta :
delta: 7.58515e-06
beta: 1.75498e-07


xrh: 0.475927E-05
xih: 0.289862E-06

Miller_h: 4
Miller_k: 4
Miller_l: 4

# crystal thickness in microns
thickness: 50 
separation1: 0
separation2: 0
#Grid parameters
xgrid: 3200
ygrid: 1

#size in micron
xxmax: 1200 
yymax: 10
#yymax: 10 

x00: -500


M: 'auto'
tpad: 4096

#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.05
method: 'Verlet'
#Mode: TIDP, TDP
mode: 'TIDP'

beam: 'Gaussian'
waist: 250.0

#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0


#Deformation of lattice: None, Sinusoidal, 
deformation: 'None'

def_amplitude: 0.5e-10
def_period: 4.0
def_B: 0.25
#program settings

nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 5

