#=============================================
# Define Crystal Parameters
#=============================================

omega0: 14400  #central photon energy

a0: 3.5668194616854 #Diamond lattice constant in A

#  Refraction index = 1 - delta - i*beta :

delta1: 3.520975e-06
beta1: 1.45485e-09
xrh1:  0.155388E-05
xih1:  0.270050E-08

delta2: 3.520975e-06
beta2: 1.45485e-09
xrh2:  0.155388E-05
xih2:  0.270050E-08


Miller_h: 4
Miller_k: 4
Miller_l: 0

# crystal thickness in microns
thickness: 20
d_film: 0
xs: 0   # moving crystal 0 um with respect to origin in x-coordinate
separation1: 0
separation2: 0
asymm_angle: 0
#Grid prameters
xgrid: 4000
ygrid: 1
#geometry: 'from_file'
#geometry_file: 'Asymm.geom.npy'
geometry: 'not_from_file'
geometry_file: 'Asymm.geom.npy'

#size in micron
xxmax: 100 
yymax: 150
#yymax: 10 



tpad: 512


#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.006666
method: 'Euler'

#Mode: TIDP, TDP
mode: 'TIDP'
M: 2500
#M: 'auto'
beam: 'Gaussian'
slit_x: 10 # microns slit width
slit_y: 100000 # microns slit width
waist: 4000.0
# x00: 'auto'
x00: -50
#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0


#Deformation of lattice: None, Sinusoidal, 
#deformation: 'None'
deformation: 'Bent Spectrometer'
strain: 0
def_B: 0.25  # strain gradient parameter
R: 0.095 # crystal bend redius in m
vC100: 0.008 #the Poisson ratio
def_amplitude: 0.0
def_period: 4.0

x0d: 0
y0d: -0 #y coordinate of dislocatio in um
z0d: -0 #z coordinate of dislocatio in um
slope: 0.0
phid: 1.5707963267948966 #orientation of dislocation
#phid: 0 #orientation of dislocation
burgers_vector_x: 1.9200423982948915 # a0/2/sqrt(2) in A, x-component mixed 60 deg dislocation 
burgers_vector_screw: 3.840084796589783 # a0/sqrt(2) in A           
vC: 0.22 # Poisson ratio
dudz: 0.00
depth: 0
B_size: 100
CrSize: 800000
def_amplitude: 0.5e-10
def_period: 4.0
def_B: 0.25
#program settings
nthread_fft: 4
quiet_mode: True
store_fields: True
zsep: 10
