#=============================================
# Define Crystal Parameters
#=============================================

omega0: 12000.0  #central photon energy

a0: 5.4307 #Si lattice constant in A

#  Refraction index n = 1 - delta - i*beta :
#data from https://x-server.gmca.aps.anl.gov/cgi/

delta1: 0.33814E-05
beta1:  0.36097E-07
xrh1: 0.34306E-05
xih1: 0.67043E-07

delta2: 0.33814E-05
beta2:  0.36097E-07
xrh2: 0.34306E-05
xih2: 0.36097E-07


Miller_h: 4
Miller_k: 0
Miller_l: 0


d_film: 0
xs: 0   # moving crystal 0 um with respect to origin in x-coordinate
# crystal thickness in microns and
thickness: 300
asymm_angle: 90.0 #deg
width: 100

#Grid parameters, number of grid points
xgrid: 300
ygrid: 128

# simulation  window size in micron
xxmax: 300 
yymax: 100
#yymax: 10 

#Integration methods: Euler, Verlet, Forest-Ruth
Zstep_factor: 0.05 #  defined as:
 #Z = np.abs(Zstep_factor * np.pi/np.real((delta - 1i*beta)**2))/k  #  Z - step in z
method: 'Verlet'
#Mode: TIDP, TDP
mode: 'TIDP'
# number of propagation steps
M: 1700
#M: 'auto'
tpad: 4096
# type of x-ray beam
beam: 'Gaussian'

slit_x: 10000 # microns slit width
slit_y: 10000 # microns slit widt
# x00: 'auto'
x00: -140  # initial beam position in microns
waist: 4000 #microns
slit_x: 250 # microns slit width
slit_y: 100000 # microns slit width
#pump from file GenesisV2

# beam: 'GenesisV2'
# fname_GenV2: 'pump-test-GenV2.dfl'
# ncar_GenV2: 251
# dgrid_GenV2: 1.2e-3
# mag_factor_GenV2: 1.0
# zsep_GenV2: 40
# crop_t: 1.0
# crop_x: 1.0

#geometry: 'from_file'
geometry: 'from_file'
geometry_file: 'SiFinite.geom.npy'

#Deformation of lattice: None, Sinusoidal, 

deformation: 'None'
strain: 0
x0d: 0
y0d: -0 #y coordinate of dislocatio in um
z0d: -0 #z coordinate of dislocatio in um
slope: 0.0
phid: 1.5707963267948966 #orientation of dislocation
#phid: 0 #orientation of dislocation
burgers_vector_x: 1.9200423982948915 # a0/2/sqrt(2) in A, x-component mixed 60 deg dislocation 
burgers_vector_screw: 3.840084796589783 # a0/sqrt(2) in A           
vSi: 0.22 # Poisson ratio
dudz: 0.00
depth: 0
B_size: 100
CrSize: 100
def_amplitude: 0.5e-10
def_period: 4.0
def_B: 0.25
#program settings
nthread_fft: 256
quiet_mode: True
store_fields: True
zsep: 1